version: 0.1.{build}
skip_tags: true
os: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 2
test: off
branches:
  only:
  - master
environment:
  NuGetApiKey:
    secure: <Set Key here!>
build_script:
- ps: .\build.ps1
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\**\*.zip
- path: artifacts\*.xml
- path: artifacts\*.html
- path: artifacts\*.exe
notifications:
- provider: Email
  to:
  - robin@getgreenshot.org
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
